language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: psQuWVE7MWmieifME3SudCzq5fL2gGMpACwokncLnMsBEYlbvrqDpPwzQ7IMyolJFtYTX4oZ1fz/HQDgI15F8pDzgi69foFO68zKilaDjkLG5j1HkrIkCK+bFaTP30sq0gYITqNtuE13nTwsVSKxbFnH2ofLYAff0VoiEpOht7bf5gJbST7181r4WLh0lgugsuSOadvCdeOhF8qMWWBJztrPzcRoZPW4OaCMvCQun9AvAp3JrYv6BpMcOcBt11Ev3TGY7Gy7TkTg6L2wKWHFp6clcqCJJXkVc6ngjmCLFUjNesuK3WepNfHfO96FC7GHx8iEMdx95dNKuOOx7toqvbJ3jeGMHrg8FtS3w3jiIIWGmT2lwJc/u9eZCe+SPLJODydsSv0A1YBMB5uFNdOz87vOBgxQYtz051nKPKe+eiRiBRljN3oeJ7BsGxFTjMeCEWuaczsyKmjdLkMAtn6gPAJAyt7ouj46BMdwcYIN29RgT/VEPbHAZOTY70zaqAtK5yeAmNrOfqMVX7t5xFr6JkXGRgCipilZWBeqNgn6hpo/tNMbHKVRaEfBY+VyV6HwquJQcEO4ei1jTqEjuy4YwpUONWW2gB9qCo9tE1YDfjzPzw+kAI092LWUFNf5gvOdQzfT6ynOoyKzFglIg70aFKCkuU8M67vOshoKsYSITzU=
  app: isaacdevops-pipeline
  edge: true
